# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: MIT-0

version = 1

[[annotations]]
SPDX-FileCopyrightText = "2025 Samuel Wu and contributors"
SPDX-License-Identifier = "MIT"
path = ["docs/**", "tests/*_test/**"]

[[annotations]]
SPDX-FileCopyrightText = "2025 Samuel Wu"
SPDX-License-Identifier = "MIT-0"
path = [
    ".github/ISSUE_TEMPLATE/*.md",
    ".python-version",
    ".vscode/*.json",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "CONTRIBUTORS.md",
    "README.md",
    "tox.ini",
    "uv.lock",
]

[[annotations]]
SPDX-FileCopyrightText = "2014 Coraline Ada Ehmke"
SPDX-License-Identifier = "CC-BY-4.0"
path = ["CODE_OF_CONDUCT.md"]

[[annotations]]
SPDX-FileCopyrightText = "2021 TakWolf"
SPDX-License-Identifier = "OFL-1.1"
path = ["tests/fmp_test/**"]
precedence = "override"
